### ISSUE TITLE
Plugin name

### ISSUE THREAD

**Issue by AbuBaniaz** [oe-alliance/XMLTV-Import#3]
Can we change the name to EPG-Importer please?

**Comment by RobvanderDoes** [comment]
That should indeed be done: this is confusing.
The install location is now "/enigma2/python/Plugins/Extensions/EPGImport", it shows as "EPG importer", but the _plugin's_ name is (still) "enigma2-plugin-extensions-xmltvimport".

**Comment by Schimmelreiter** [comment]
I kept the name as OpenPLi did to match that.
We can of course change the name, but then people will start asking why oe-a doesn't have xmltvimport like OpenPLi has ...

**Comment by RobvanderDoes** [comment]
Not everything PLi does is good :)
You always get questions. Now we get questions like we can't find 'EPG-importer' (to install or de-install), and that's correct, as it doesn't exist.

t.b.h.: I would never have changed the name from 'XMLTV'  to 'EPG-import' in the first place.

**Comment by Schimmelreiter** [comment]
Personally I don't care about if its xmltvimport or epgimport on the feed, but I strongly suggest to keep it as EPG-Importer inside the menu.
Joe Average doesn't care if it originates from xmltv-, csv-, html- or whatever technical format but about what it does ...

**Comment by RobvanderDoes** [comment]
But your 'Joe Average' now has to find 'XMLTV-import' on the feeds to get 'EPG-importer' on his box.... 
Personally I don't care about the name in the menu; it has always been clear and it still is.
I care about consistency; once a name is in place it should show the same everywhere.

**Comment by Schimmelreiter** [comment]
Did you notice I didn't disagree?
You are right, it is inconsistent.

And I couldn't agree more when you say "Not everything PLi does is good", I wouldn't have switched to OpenATV else.

I just forecast a lot of user questions when this widely used extension has a different name in oe-a compared to that in PLi. Because PLi is still one of the most widely used Enigmas, so a lot, if not most, users switching to oe-a images have been using PLi before and got used to its oddities.

Suggestion:
Why not simply rename this plugin to "epgimport" on the feed and add a dummy package "xmltvimport" which RDEPENDS on "epgimport"?

I think that would make everyone happy.

**Comment by AbuBaniaz** [comment]
"EPG-Importer" would be the better name as that is what it says on the screen.

**Comment by RobvanderDoes** [comment]
Why all the fuss?
If you want to be different from PLi, why do you want to look like PLi? We (OE-A images) have a different identity from PLi, and personally I'm not too shy to show that. And if people don't like that, they should revert to PLi, simple as that.
And don't forget: we all have forums, on which we give plenty of support for those who have issues.
So IMHO: simply change the name to the one that shows on the GUI.

**Comment by RobvanderDoes** [comment]
Not solved yet, so re-opened.

**Comment by RobvanderDoes** [comment]
Done, & closed.
